---
- name: Provision production web setup
  hosts: local
  connection: local
  vars_files:
  - vars.yml
  - [ 'secrets.yml', 'secrets.vault.yml' ]
  tasks:

    - name: Provision production web load balancer
      rax_clb:
        credentials: ~/.rackspace_cloud_credentials
        name: "{{ deployment_region }}_prod_{{ server_name }}"
        port: 80
        protocol: HTTP
        algorithm: ROUND_ROBIN
        type: PUBLIC
        timeout: 30
        region: "{{ deployment_region }}"
        ssl_termination:
          private_key: "{{ production_ssl_key }}"
          certificate: "{{ production_ssl_certificate }}"
          intermediate_certificate: "{{ production_intermediate_certificate }}"
          secure_traffic_only: yes
        https_redirect: yes
        wait: yes
        state: present
      register: clb_prod

    - name: Provision 2 production web servers
      rax:
        credentials: ~/.rackspace_cloud_credentials
        name: "{{ deployment_region }}_prod_webserver_%01d"
        flavor: performance1-1
        image: ubuntu-1204-lts-precise-pangolin
        networks:
          - public
          - private
        region: "{{ deployment_region }}"
        state: present
        count: 2
        exact_count: yes
        group: prod_webservers
        wait: yes
        key_name: drg
      register: rax_prod

    - name: Add web servers to load balancer
      rax_clb_nodes:
        credentials: ~/.rackspace_cloud_credentials
        load_balancer_id: "{{ clb_prod.balancer.id }}"
        address: "{{ item.rax_networks.private|first }}"
        port: 80
        condition: enabled
        type: primary
        wait: yes
        region: "{{ deployment_region }}"
      with_items: rax_prod.success
      when: rax_prod.action == 'create'

    - name: Add web servers to prod_webservers host group
      add_host:
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.rax_accessipv4 }}"
        groupname: prod_webservers
      with_items: rax_prod.success
      when: rax_prod.action == 'create'

    - name: Ensure the CDN container exists
      rax_files:
        username: "{{ rackspace_username }}"
        api_key: "{{ rackspace_apikey }}"
        region: "{{ common_region }}"
        container: "{{ production_container }}"
        state: present
        ttl: "{{ cdn_ttl }}"
        public: yes

- name: Configure web server(s)
  hosts: prod_webservers
  remote_user: root
  vars_files:
  - vars.yml
  - [ 'secrets.yml', 'secrets.vault.yml' ]
  vars:
    docroot: /var/www/html/developer.rackspace.com
    backendroot: /var/webapp/drc-backend
    mailgun_domain: "{{ production_mailgun_domain }}"
    sponsorship_notification_email: "{{ production_sponsorship_notification_email }}"
    sponsorship_container: "{{ production_sponsorship_container }}"
    mongodb_connection_url: "{{ production_mongodb_connection_url }}"
  roles:
    - prod
    - webserver
    - lockboxweb
    - editors
    - "{{ nginx_role_config }}"
