---
- name: Provision production web setup
  hosts: local
  connection: local
  vars_files:
  - vars.yml
  - [ 'secrets.yml', 'secrets.vault.yml' ]
  tasks:

    - name: Provision production web load balancer
      rax_clb:
        credentials: ~/.rackspace_cloud_credentials
        name: "{{ deployment_region }}_prod_{{ server_name }}"
        port: 80
        protocol: HTTP
        algorithm: ROUND_ROBIN
        type: PUBLIC
        timeout: 30
        region: "{{ deployment_region }}"
        ssl_termination:
          private_key: "{{ production_ssl_key }}"
          certificate: "{{ production_ssl_certificate }}"
          intermediate_certificate: "{{ production_intermediate_certificate }}"
          secure_traffic_only: yes
        https_redirect: yes
        wait: yes
        state: present
      register: clb_prod

    - name: Provision 2 production web servers
      rax:
        credentials: ~/.rackspace_cloud_credentials
        name: "{{ deployment_region }}_prod_webserver_%01d"
        flavor: performance1-1
        image: ubuntu-1204-lts-precise-pangolin
        networks:
          - public
          - private
        region: "{{ deployment_region }}"
        state: present
        count: 2
        exact_count: yes
        group: prod_webservers
        wait: yes
        key_name: drg
      register: rax_prod

    - name: Add web servers to load balancer
      rax_clb_nodes:
        credentials: ~/.rackspace_cloud_credentials
        load_balancer_id: "{{ clb_prod.balancer.id }}"
        address: "{{ item.rax_networks.private|first }}"
        port: 80
        condition: enabled
        type: primary
        wait: yes
        region: "{{ deployment_region }}"
      with_items: rax_prod.success
      when: rax_prod.action == 'create'

    - name: Add web servers to prod_webservers host group
      add_host:
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.rax_accessipv4 }}"
        groupname: prod_webservers
      with_items: rax_prod.success
      when: rax_prod.action == 'create'

    - name: Ensure the CDN container exists
      rax_files:
        username: "{{ rackspace_username }}"
        api_key: "{{ rackspace_apikey }}"
        region: "{{ common_region }}"
        container: "{{ production_container }}"
        state: present
        ttl: "{{ cdn_ttl }}"
        public: yes

- name: Configure web server(s)
  hosts: prod_webservers
  remote_user: root
  vars_files:
  - vars.yml
  - [ 'secrets.yml', 'secrets.vault.yml' ]
  vars:
    mailgun_domain: "{{ production_mailgun_domain }}"
    sponsorship_notification_email: "{{ production_sponsorship_notification_email }}"
    sponsorship_container: "{{ production_sponsorship_container }}"
    mongodb_connection_url: "{{ production_mongodb_connection_url }}"
  roles:
    - prod
    - webserver
    - lockboxweb
    - editors
    - role: bennojoy.nginx
      nginx_http_params:
        sendfile: "on"
        access_log: /var/log/nginx/access.log
        client_max_body_size: 50m
        server_tokens: "off"
        more_set_headers: '"Server: Nintendo WiiOS; Server 1.up"'
      nginx_sites:
      - server:
          gzip_static: "on"
          file_name: developer.rackspace.com
          listen: 80
          server_name: "{{ server_name }}"
          root: "{{ docroot }}"
          gzip: "on"
          gzip_min_length: 1400
          gzip_types: text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript
          gzip_vary: "on"
          gzip_proxied: any
          location1:
            name: /api
            proxy_pass: http://127.0.0.1:8111
          location2:
            name: /blog/index.html
          location3:
            name: /blog
            rewrite: "^/blog/([^/]+)\\.html$ /blog/$1/ permanent"
          location4:
            name: /devtrial
            rewrite: "^/devtrial /signup/ permanent"
          location5:
            name: /speed
            rewrite: "^/speed /signup/ permanent"
