# Master playbook to provision and bootstrap all production and staging servers.
---

- include: prod_web.yml server_name=developer.rackspace.com

- include: staging_web.yml server_name=staging-developer.rackspace.com

- include: jenkins.yml
