---
# Paths that should be common across playbooks.

# Rackspace region in which the CDN and sponsorship form upload containers should be created.
common_region: IAD

# Zones from which monitoring checks will be performed.
monitoring_zones:
- mzdfw
- mziad
- mzord

# Destination container for production static assets.
production_container: drc-static-prod

# Destination container for staging static assets.
staging_container: drc-static-staging

# TTL value for CDN containers.
cdn_ttl: 31536000

# Deployment region, parsed from environment variable and normalized
deployment_region: "{{ lookup('env', 'RAX_REGION') | upper }}"

nginx_role_config:
  role: bennojoy.nginx
  nginx_http_params:
    sendfile: "on"
    access_log: /var/log/nginx/access.log
    client_max_body_size: 50m
    server_tokens: "off"
    more_set_headers: '"Server: Nintendo WiiOS; Server 1.up"'
  nginx_sites:
  - server:
      gzip_static: "on"
      file_name: developer.rackspace.com
      listen: 80
      server_name: "{{ server_name }}"
      root: "{{ docroot }}"
      gzip: "on"
      gzip_min_length: 1400
      gzip_types: text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript
      gzip_vary: "on"
      gzip_proxied: any
      location1:
        name: /api
        proxy_pass: http://127.0.0.1:8111
      location2:
        name: /blog/index.html
      location3:
        name: /blog
        rewrite: "^/blog/([^/]+)\\.html$ /blog/$1/ permanent"
      location4:
        name: /devtrial
        rewrite: "^/devtrial /signup/ permanent"
      location5:
        name: /speed
        rewrite: "^/speed /signup/ permanent"
      location6:
        name: /categories
        rewrite: "^/categories/([^/]+)/*$ /blog/categories/$1/ permanent"
