---
- name: Install java
  apt: pkg={{ item }} update_cache=yes state=present
  sudo: yes
  with_items:
  - openjdk-7-jdk
  - openjdk-7-jre

- name: Download Elasticsearch
  get_url: url={{elasticsearch_download_baseurl}}{{elasticsearch_package_filename}} dest=/tmp/{{elasticsearch_package_filename}}

- name: Install Elasticsearch
  command: dpkg -i /tmp/elasticsearch-{{elasticsearch_version}}.deb
  sudo: yes

- name: Start Elasticsearch service
  service: name=elasticsearch state=started
  sudo: yes
